import React, {useEffect, useState} from 'react';
import Head from 'next/head';
import { Box } from '@mui/system';
import ReportComponent from '../components/ReportComponent';
import { Grid } from '@mui/material';
import 'gridstack/dist/gridstack.min.css';
import { GridStack } from 'gridstack';

export default function Home({loadedUser, setIsLoading, currentUser, setOpenLoginModal}) {

  const [paymentLink, setPaymentLink] = useState("");

  const [showInvoicePayment, setShowInvoicePayment] = useState(false);
  const [invoicePayload, setInvoicePayload] = useState(null);
  const [ticketId, setTicketId] = useState(null);

  const [editorContent, setEditorContent] = useState("<b>Test</b>");

  return (
    <Box>
      <Head>
        <title>Welcome to AuthScape Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div class="grid-stack"></div>

    </Box>
  )
}
