import React, {useEffect, useState} from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import {authService} from 'authscape';
import Button from '@mui/material/Button';

export default function Home({loadedUser, currentUser}) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {currentUser == null &&
        <>
          <Button variant="contained" onClick={async () => {
            await authService().login();
          }}>Login</Button>
          <Button variant="contained" onClick={async () => {

            await authService().signUp();

          }}>Create Account</Button>
        </>
      }

      {currentUser != null &&
      <>
        <div>
          Welcome {currentUser.firstName}!
        </div>

        <Button variant="contained" onClick={async () => {
            await authService().logout();
          }}>Logout</Button>
      </>
      }
      
    </div>
  )
}
