import React, {useEffect, useState, useCallback} from 'react';
import Head from 'next/head';
import { Box } from '@mui/system';
import {GoogleMaps, GoogleMapsHeatmap, Overview} from 'authscape';

export default function Maps() {

  const heatMapData = [
    { lat: 35.6895, lng: 139.6917, weight: 100, name:"Look at me" }, // Tokyo
    { lat: 34.0522, lng: -118.2437, weight: 200, name:"great" }, // Los Angeles
    { lat: 51.5074, lng: -0.1278, weight: 500, name:"weweezzzer" }, // London
  ];

  return (
  <div>
    <Head>
      <title>Maps</title>
      <meta name="description" content="Generated by AuthScape" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    Basic Example (with overlay)
    <Box sx={{ flexGrow: 1, height:400 }}>
      <GoogleMaps 
        apiKey={"google maps key"}
        hasLoaded={true}>

          <Overview lat={38} lng={-98}>
            <div style={{ background: 'white', border: '1px solid black', padding: '10px' }}>
              <h4>Custom Overlay</h4>
              <p>This is a custom overlay content.</p>
            </div>
          </Overview>
          
      </GoogleMaps>
    </Box>



    HeatMap Example
    <Box sx={{ flexGrow: 1, height:400 }}>
      <GoogleMapsHeatmap 
        apiKey={"google maps key"}
        data={heatMapData}
        overlay={(point) => {

          return (
            <div style={{ background: 'white', opacity:"0.9", border: '1px dashed black', padding: 8, borderBottomLeftRadius: 20, borderBottomRightRadius:20, borderTopRightRadius:20 }}>
              <h4>{point.data.name}</h4>
              <p>${point.weight.toFixed(2)}</p>
            </div>
          )

        }}>
      </GoogleMapsHeatmap>
    </Box>






  </div>
  )
}
