// pages/index.js
import Head from 'next/head';
import {ThreeScene} from '../../components/ThreeScene';

export default function Home() {
    return (
        <div>
            <Head>
                <title>My Three.js App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>Welcome to My Three.js App</h1>
                <ThreeScene />
            </main>
        </div>
    );
}
