import React, {useEffect, useState, useRef} from 'react';
import Head from 'next/head';
import { Box } from '@mui/system';
import {FileMapping} from '../../components/mapping/fileMapping';
// import {FileMapping} from 'authscape';

const Index = ({currentUser}) => {

    return (
        <Box>
          <Head>
              <title>Welcome to AuthScape</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
          </Head>

          <Box sx={{paddingTop:6}}>

            <FileMapping currentUser={currentUser} hideDocumentManager={false}

              onOpened={(documentComponentId) => {
                alert("opened: " + documentComponentId)
              }}
            
              onPublished={(documentComponentId) => {
                alert("published: " + documentComponentId);
              }}

              onCanceled={(documentComponentId) => {
                alert("canceled: " + documentComponentId);
              }}

              onArchived={(documentComponentId) => {
                alert("archived: " + documentComponentId);
              }}
            
            />

          </Box>

        </Box>
    )
}

export default Index;